import {expandProducts} from './catalog.js';
export async function loadProducts() {const response=await fetch('./data/products.json');if(!response.ok)throw new Error('商品データを読み込めませんでした');const products=await response.json();if(!Array.isArray(products)||products.some(p=>!p.id||!p.scores))throw new Error('商品データの形式が正しくありません');return expandProducts(products);}
export const hasKind=(p,kind='both')=>kind==='both'?(!!p.shampoo||!!p.treatment):!!p[kind];
export const kindItems=(p,kind='both')=>[['shampoo','シャンプー'],['treatment','トリートメント']].filter(([key])=>kind==='both'||key===kind).filter(([key])=>p[key]).map(([key,label])=>({key,label,item:p[key],image:p.kind?p.image:p.images?.[key==='shampoo'?0:1]||p.image}));
export const unitPrice=(p,kind='both')=>{const values=kindItems(p,kind).map(x=>x.item.price);return values.length&&values.every(x=>typeof x==='number')?Math.max(...values):null;};
export const priceLabel=n=>typeof n==='number'?`¥${n.toLocaleString('ja-JP')}（税込）`:'価格未確認';
export function filterProducts(products,f={}) {const kind=f.kind||'both';return products.filter(p=>hasKind(p,kind)&&(!f.brand||p.brand===f.brand)&&(!f.series||p.series===f.series)&&(!f.q||[p.name,p.brand,p.series,p.shampoo?.name,p.treatment?.name].join(' ').toLowerCase().includes(f.q.toLowerCase()))&&(!f.category||p.category===f.category)&&(!f.price||(unitPrice(p,kind)!==null&&unitPrice(p,kind)<=Number(f.price)))&&(!f.hair||p.scores[f.hair]>=80)&&(!f.finish||p.scores[f.finish]>=80)&&(!f.squeak||p.scores.lowSqueak>=85)&&(!f.scent||p.fragrance.type.includes(f.scent)));}

export function productView(p,kind='both') {if(p.kind)return p;const items=kindItems(p,kind);return {...p,shampoo:kind==='treatment'?null:p.shampoo,treatment:kind==='shampoo'?null:p.treatment,image:items[0]?.image||p.image,images:items.map(x=>x.image)};}
