import {priceLabel} from './products.js';
import {kindItems,productView} from './products.js';
import {labels} from './diagnosis.js';
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2',bookmark:'M6 3h12v18l-6-4-6 4V3Z',home:'M3 11 12 3l9 8M5 10v11h5v-6h4v6h5V10',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',compare:'M5 4v16M12 4v16M19 4v16M2 8h6M9 15h6M16 10h6',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',back:'m15 5-7 7 7 7',arrow:'M4 12h16m-6-6 6 6-6 6',shop:'M3 9h18l-2-6H5L3 9Zm1 0v12h16V9M9 21v-7h6v7',scissors:'m7 8 13 13M7 16 20 3M8 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 18a3 3 0 1 1-6 0 3 3 0 0 1 6 0',bag:'M5 7h14l2 14H3L5 7Zm3 0V5a4 4 0 0 1 8 0v2',check:'m5 12 4 4L19 6'};
export const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.spark}"/></svg>`;
export const categoryLabel=p=>p.category==='salon'?'サロン系':'市販系';
export const badge=p=>`<span class="badge">${categoryLabel(p)}</span>${p.kind?`<span class="badge product-kind">${p.kind==='shampoo'?'シャンプー':'トリートメント'}</span>`:''}<span class="badge muted-badge">相性は仮評価</span>`;
export function nav(route,count){const active=['compare','favorites','saved'].includes(route)?'saved':['mypage','history'].includes(route)?'mypage':route==='results'?'diagnosis':route;return [['home','home','ホーム'],['diagnosis','spark','診断'],['search','search','商品検索'],['saved','bookmark','保存'],['mypage','user','マイページ']].map(([url,i,label])=>`<a href="#${url}" ${active===url?'aria-current="page"':''}>${icon(i)}<span>${label}</span></a>`).join('');}
export function metrics(result,compact=false){const entries=Object.entries(labels).filter(([k])=>['manageable','soft','smooth','silky','moist','lowSqueak','curlyHair','damageRepair','fragrance','cost'].includes(k)&&!(result.product?.kind==='treatment'&&k==='lowSqueak'));return `<div class="metrics">${(compact?entries.filter(([k])=>['manageable','soft','lowSqueak','fragrance','cost'].includes(k)):entries).map(([key,label])=>`<div class="metric"><span>${label}</span><div class="bar"><i style="width:${result.metrics[key]??0}%"></i></div><b>${result.metrics[key]===null?'—':Math.round(result.metrics[key])}</b></div>`).join('')}</div>`;}
export function productCard(p,state,result=null,rank=null){p=productView(p,state.viewKind||'both');return `<article data-product-id="${p.id}" class="product-card ${rank===1?'winner':''}">${rank?`<span class="rank">${rank}<small>位</small></span>`:''}<div class="product-top"><a href="#detail/${p.id}" class="product-image">${productPhotos(p)}</a><div class="product-info">${result?`<span class="match">あなたとの相性 <b>${result.score}%</b></span>`:''}<p class="eyebrow">${esc(p.brand)}</p><a class="product-name" href="#detail/${p.id}">${esc(p.name)}</a><p class="small">${esc(p.series)}</p><div class="badges">${badge(p)}</div><p class="small">${[p.shampoo?'シャンプー':null,p.treatment?'トリートメント':null].filter(Boolean).join(' / ')}<br>${[p.shampoo,p.treatment].filter(Boolean).map(item=>`${priceLabel(item.price)} / ${item.volume||'容量未確認'}`).join('<br>')}</p></div></div>${rank===1?metrics(result,true)+`<div class="reason"><b>あなたに合う理由</b><p>${esc(result.reasons[0])}</p></div>`:''}<div class="card-actions"><a class="button outline" href="#detail/${p.id}">詳細を見る ${icon('arrow')}</a><button class="icon-button ${state.favorites.includes(p.id)?'hearted':''}" data-action="favorite" data-id="${p.id}" aria-label="${esc(p.name)}をお気に入り${state.favorites.includes(p.id)?'から削除':'に追加'}" aria-pressed="${state.favorites.includes(p.id)}">${icon('heart')}</button><button class="icon-button ${state.compare.includes(p.id)?'selected':''}" data-action="compare" data-id="${p.id}" aria-label="${esc(p.name)}を比較${state.compare.includes(p.id)?'から削除':'に追加'}" aria-pressed="${state.compare.includes(p.id)}">${icon('compare')}</button></div></article>`;}
export function heading(title,sub='',back='home'){return `<div class="page-top"><a href="#${back}" class="icon-button" aria-label="戻る">${icon('back')}</a><span>HairMatch</span><span class="tiny">HAIR CARE FINDER</span></div><h1>${title}</h1>${sub?`<p class="description">${sub}</p>`:''}`;}
export function empty(title,text,link='search',button='商品を探す'){return `<div class="empty">${icon('search')}<h2>${title}</h2><p>${text}</p><a class="button primary" href="#${link}">${button} ${icon('arrow')}</a></div>`;}


export function productPhotos(p){return `<div class="product-photo">${(p.images?.length?p.images:[p.image]).map((url,i)=>`<img src="${esc(url)}" alt="${esc(p.name)} ${p.images?.length>1?(i===0?'シャンプー':'トリートメント'):''}" loading="lazy">`).join('')}</div>`;}
export function sourcesHTML(p){return (p.sources||[]).length?`<p class="source-note">公式情報確認日：${esc(p.checkedAt)}。価格は参考税込価格です。</p><div class="source-list">${p.sources.filter(s=>/^https:\/\//.test(s.url)).map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a>`).join('')}</div>`:'';}
