import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {chromeSession} from '../scripts/chrome-session.mjs';
const c=await chromeSession(),{send,evaluate}=c;
const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,80));}throw Error('Timeout '+expression);};
const click=async selector=>{assert.ok(await evaluate(`!!document.querySelector(${JSON.stringify(selector)})`),selector);await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);};
const cards=()=>evaluate(`document.querySelectorAll('#search-results .product-card').length`);
const snap=async name=>{await fs.mkdir('test-results',{recursive:true});await fs.writeFile('test-results/'+name+'.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));};
try{
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:'http://127.0.0.1:4173/#search'});await wait(`!!document.querySelector('.brand-grid')`);assert.equal(await evaluate(`document.querySelectorAll('.brand-card').length`),6);assert.equal(await cards(),0);assert.equal(await evaluate(`getComputedStyle(document.querySelector('#search-input')).fontSize`),'16px');await snap('brand-directory-mobile');
 for(const brand of ['BOTANIST','YOLU','COTA','KERASTASE','&honey','plus eau']){
  await click(`[data-action="search-brand"][data-value="${brand}"]`);assert.ok(await cards()>0);assert.ok(await cards()<=12);assert.equal(await evaluate(`document.querySelector('.catalog-controls h2').textContent`),brand);
  await click('[data-action="view-kind"][data-value="treatment"]');assert.ok(await evaluate(`[...document.querySelectorAll('#search-results .product-card')].every(p=>p.textContent.includes('トリートメント'))`));await click('[data-action="view-kind"][data-value="both"]');
  if(brand==='COTA'){
   await click('[data-action="search-page"][data-value="2"]');const before=await evaluate(`[...document.querySelectorAll('.product-card')].map(p=>p.dataset.productId)`);await click('.product-card .product-name');await wait(`!!document.querySelector('.detail-page')`);await click('.page-top a');await wait(`!!document.querySelector('#search-input')`);assert.deepEqual(await evaluate(`[...document.querySelectorAll('.product-card')].map(p=>p.dataset.productId)`),before);await snap('brand-products-mobile');
  }
  if(brand==='plus eau'){
   assert.deepEqual(await evaluate(`[...document.querySelectorAll('.product-card')].map(p=>p.dataset.productId)`),['plus-mellow-shampoo','plus-mellow-treatment','plus-melty-shampoo','plus-melty-treatment','plus-repair-shampoo','plus-repair-treatment','plus-lyporm-shampoo','plus-lyporm-treatment']);
   await snap('plus-series-order-mobile');
   await evaluate(`var sel=document.querySelector('[data-filter="series"]');sel.value='リポア';sel.dispatchEvent(new Event('change',{bubbles:true}));`);assert.equal(await cards(),2);await click('[data-action="favorite"][data-id="plus-repair-treatment"]');await click('[data-action="compare"][data-id="plus-repair-treatment"]');await click('[data-action="search-directory"]');await click('[data-action="search-brand"][data-value="BOTANIST"]');await click('[data-action="favorite"][data-id="botanist-moist-shampoo"]');await click('[data-action="compare"][data-id="botanist-moist-shampoo"]');
  }
  await click('[data-action="search-directory"]');
 }
 await click('[data-action="search-all"]');let seen=[];while(true){seen.push(...await evaluate(`[...document.querySelectorAll('.product-card')].map(p=>p.dataset.productId)`));const last=await evaluate(`document.querySelector('.pagination [data-action="search-page"]:last-child').disabled`);if(last)break;await click('.pagination [data-action="search-page"]:last-child');}assert.equal(seen.length,85);assert.equal(new Set(seen).size,85);
 await evaluate(`document.querySelector('#search-input').value='該当なし';document.querySelector('#search-input').dispatchEvent(new Event('input',{bubbles:true}));`);assert.equal(await cards(),0);await click('.empty [data-action="reset-filters"]');assert.equal(await evaluate(`document.querySelectorAll('.brand-card').length`),6);
 await evaluate(`location.hash='compare'`);await wait(`!!document.querySelector('table')`);assert.equal(await evaluate(`document.querySelectorAll('thead th').length`),3);await click('[data-action="view-kind"][data-value="shampoo"]');assert.equal(await evaluate(`document.querySelectorAll('thead th').length`),2);await click('[data-action="view-kind"][data-value="treatment"]');assert.equal(await evaluate(`document.querySelectorAll('thead th').length`),2);await click('[data-action="view-kind"][data-value="both"]');
 await evaluate(`location.hash='favorites'`);await wait(`document.querySelectorAll('.product-card').length===2`);await send('Page.reload');await wait(`document.querySelectorAll('.product-card').length===2`);
 // Decode every image, including products on later pages.
 const imageCheck=await evaluate(`(async()=>{const raw=await(await fetch('./data/products.json')).json();const urls=[...new Set(raw.flatMap(p=>p.images))];for(const url of urls){const im=new Image();im.src=url;await im.decode();if(im.naturalWidth!==600||im.naturalHeight!==600)throw Error(url);}return urls.length})()`);assert.equal(imageCheck,85);
 for(const width of [320,390,768,1440]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<768});await evaluate(`location.hash='search'`);await wait(`!!document.querySelector('.brand-grid')`);assert.equal(await evaluate(`document.documentElement.scrollWidth>innerWidth`),false);await click('[data-action="search-brand"][data-value="KERASTASE"]');assert.equal(await evaluate(`document.documentElement.scrollWidth>innerWidth`),false);if(width===1440)await snap('brand-products-desktop');await click('[data-action="search-directory"]');}
 assert.deepEqual(c.errors,[]);console.log('PASS: 6 brands / 85 images / pagination / return / independent favorites & comparison / 320–1440px / 16px input');
}finally{c.close();}
