import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {expandProducts,sortCatalog} from '../js/catalog.js';import {filterProducts} from '../js/products.js';import {rankProducts} from '../js/diagnosis.js';import {brandGroups,pageProducts,PAGE_SIZE,seriesOptions,reconcileSeries} from '../js/search.js';
const products=expandProducts(JSON.parse(fs.readFileSync(new URL('../data/products.json',import.meta.url))));
test('ブランド内のメルティを検索せずに選べ、各種別の件数が一致する',()=>{for(const kind of ['both','shampoo','treatment']){const option=seriesOptions(products,'plus eau',kind).find(o=>o.value==='メルティ');assert.equal(option.label,'メルティ（ピンク）');assert.equal(option.count,kind==='both'?2:1);}});
test('種類変更で存在しなくなるシリーズ条件を除き、有効な条件は保持する',()=>{const before={brand:'plus eau',series:'カラーケア',price:'2000'};assert.deepEqual(reconcileSeries(products,before,'shampoo'),{brand:'plus eau',price:'2000'});assert.equal(before.series,'カラーケア');const valid={brand:'plus eau',series:'メルティ',q:'ピンク'};assert.equal(reconcileSeries(products,valid,'shampoo'),valid);for(const brand of brandGroups(products))for(const option of seriesOptions(products,brand.brand))for(const kind of ['shampoo','treatment']){const filters=reconcileSeries(products,{brand:brand.brand,series:option.value},kind);if(filters.series)assert.ok(filterProducts(products,{...filters,kind}).length>0);}});
test('6ブランドそれぞれの単品を重複なく一覧にする',()=>{const groups=brandGroups(products);assert.equal(groups.length,6);assert.equal(groups.reduce((n,g)=>n+g.products.length,0),products.length);for(const brand of ['BOTANIST','YOLU'])for(const kind of ['shampoo','treatment'])assert.ok(filterProducts(products,{brand,kind}).length>0);});
test('ブランド・シリーズ・種別を組み合わせて絞り込める',()=>{const r=filterProducts(products,{brand:'plus eau',series:'リポア',kind:'treatment'});assert.equal(r.length,1);assert.ok(r.some(p=>p.id==='plus-repair-treatment'));assert.equal(filterProducts(products,{brand:'YOLU',q:'COTA'}).length,0);});
test('全ページをたどると全商品を一度ずつ表示し、範囲外ページは補正する',()=>{const ids=[];for(let page=1;page<=Math.ceil(products.length/PAGE_SIZE);page++){const p=pageProducts(products,page);assert.ok(p.items.length<=12);ids.push(...p.items.map(p=>p.id));}assert.equal(ids.length,products.length);assert.equal(new Set(ids).size,products.length);assert.equal(pageProducts([],999).page,1);assert.equal(pageProducts(products,-1).page,1);assert.equal(pageProducts(products,999).page,Math.ceil(products.length/12));});
test('カラーシャンプーを除外し、残る専用ケアも通常診断には混入しない',()=>{assert.equal(products.filter(p=>p.kind==='shampoo'&&/カラーシャンプー|色素入り/.test(p.name)).length,0);const special=products.filter(p=>p.diagnosisEligible===false);assert.equal(special.length,0);const ranked=rankProducts(products,{target:'both'});for(const p of special)assert.ok(!ranked.some(x=>x.product.id===p.id));});
test('各シリーズでシャンプー→トリートメント→集中ケアの順に並ぶ',()=>{const sorted=sortCatalog(products);assert.deepEqual(sorted.filter(p=>p.brand==='plus eau').map(p=>p.id),['plus-mellow-shampoo','plus-mellow-treatment','plus-melty-shampoo','plus-melty-treatment','plus-repair-shampoo','plus-repair-treatment','plus-lyporm-shampoo','plus-lyporm-treatment']);for(const group of [...new Set(sorted.map(p=>p.brand+'|'+p.catalogGroup))]){const list=sorted.filter(p=>p.brand+'|'+p.catalogGroup===group);const firstTreatment=list.findIndex(p=>p.kind==='treatment');if(firstTreatment>=0)assert.ok(list.slice(firstTreatment).every(p=>p.kind==='treatment'),group);}assert.equal(filterProducts(products,{q:'ピンク'}).length,2);assert.ok(filterProducts(products,{q:'ピンク'}).every(p=>p.series==='メルティ'));});
test('公式一覧の照合台帳とシリーズごとの件数が一致する',()=>{const coverage=JSON.parse(fs.readFileSync(new URL('../data/catalog-coverage.json',import.meta.url)));for(const [brand,series] of Object.entries(coverage.groups))for(const [name,count] of Object.entries(series))assert.equal(products.filter(p=>p.brand===brand&&p.series===name).length,count,brand+' '+name);assert.equal(products.filter(p=>p.brand==='KERASTASE').length,coverage.kerastase.length);assert.equal(products.length,85);});
test('追加画像は600px正方形のPNGで統一',()=>{for(const p of products.filter(p=>p.catalogBatch)){const b=fs.readFileSync(new URL('../'+p.image,import.meta.url));assert.equal(b.toString('ascii',1,4),'PNG');assert.equal(b.readUInt32BE(16),600);assert.equal(b.readUInt32BE(20),600);}});

test('マスク・集中ケア・カラー専用商品を診断と検索から除外',()=>{for(const p of products)assert.doesNotMatch([p.name,p.shampoo?.name,p.treatment?.name,p.series].join(' '),/マスク|ヘアパック|ブースター|ホームケア|コンサントレ|クレイ|カラー|for color|ブロンド|クロマ/i);});
