import {spawn} from 'node:child_process';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const profile=path.resolve('.tmp/browser-profile-'+Date.now());await mkdir(profile,{recursive:true});await mkdir('test-results',{recursive:true});
const child=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-allow-origins=*','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;
try {
 let port;for(let i=0;i<60;i++){try{port=(await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];break;}catch{await new Promise(r=>setTimeout(r,200));}}
 if(!port)throw new Error('Chrome headless did not start');
 const targets=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});
 let sequence=0;const pending=new Map();const errors=[];
 socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p.reject(new Error(m.error.message));else p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);});
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method));},15000);pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}});socket.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
 const wait=async expression=>{for(let i=0;i<80;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,75));}throw new Error('Timed out: '+expression);};
 const click=async selector=>{assert.ok(await evaluate(`!!document.querySelector(${JSON.stringify(selector)})`),'Missing '+selector);await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);};
 const snap=async name=>{const image=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(`test-results/${name}.png`,Buffer.from(image.data,'base64'));};
﻿ const tap=async selector=>{await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center'})`);const p=await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;return {x,y,hit:e.contains(document.elementFromPoint(x,y))};})()`);assert.ok(p.hit,'Pointer blocked: '+selector);await send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y,button:'left',clickCount:1});};
 const check=(name)=>console.log('PASS: '+name);
 const atStep=async n=>wait(`document.querySelector('.progress-head>div>span')?.textContent==='${n} / 8'`);
 const choose=async values=>{for(const [key,value] of Object.entries(values))await tap(`[data-key="${key}"][data-value="${value}"]`);};
 const type=async(selector,text)=>{await tap(selector);await send('Input.insertText',{text});};
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');const failed=[];socket.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.method==='Network.responseReceived'&&m.params.response.url.startsWith('http://127.0.0.1:4173')&&m.params.response.status>=400)failed.push(m.params.response.url);});
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:'http://127.0.0.1:4173'});await wait(`!!document.querySelector('[data-action="start"]')`);
 await tap('[data-action="start"]');await atStep(1);assert.equal(await evaluate(`document.querySelector('[data-action="next"]').disabled`),true);
 await choose({category:'both'});await tap('[data-action="next"]');await atStep(2);await evaluate('history.back()');await atStep(1);await evaluate('history.forward()');await atStep(2);check('ブラウザの戻る・進むが1ステップずつ移動');
 await choose({thickness:'太い',hardness:'かなり硬い・剛毛',curl:'強いくせ毛',spread:'かなり広がりやすい'});await tap('[data-action="next"]');await atStep(3);await send('Page.reload');await atStep(3);check('再読み込みしても診断位置を保持');
 await tap('[data-action="close-diagnosis"]');await wait(`!!document.querySelector('.home')`);assert.match(await evaluate(`document.querySelector('[data-action="start"]').textContent`),/続きから再開/);await tap('[data-action="start"]');await atStep(3);check('閉じる→続きから再開');
 await choose({damage:'カラー',scalp:'普通'});await tap('[data-action="next"]');await atStep(4);
 await evaluate('window.scrollTo(0,0)');assert.equal(await evaluate(`(()=>{const r=document.querySelector('[data-action="next"]').getBoundingClientRect();return r.top>0&&r.bottom<document.querySelector('#nav').getBoundingClientRect().top;})()`),true);await snap('repaired-mobile-finish');check('長い質問でも次へが常に見える');
 await choose({finish:'soft'});await tap('[data-action="next"]');await atStep(5);await choose({squeak:'絶対に嫌',rinse:'かなり滑らか',weight:'しっとり',foam:'かなり重要'});await tap('[data-action="next"]');await atStep(6);await choose({scents:'rose',strength:'medium'});await tap('[data-action="next"]');await atStep(7);await choose({budget:'any'});await tap('[data-action="next"]');await atStep(8);
 await tap('[data-action="edit-step"][data-index="1"]');await atStep(2);await choose({thickness:'細い'});assert.match(await evaluate(`document.querySelector('[data-action="next"]').textContent`),/変更して確認/);await tap('[data-action="next"]');await atStep(8);check('回答修正後に確認画面へ直帰');
 await tap('[data-action="next"]');await wait(`!!document.querySelector('.results-page')`);assert.equal(await evaluate(`document.querySelectorAll('.results-grid .product-card').length`),5);assert.ok(await evaluate(`!!document.querySelector('.result-close [aria-label="閉じる"]')`));
 await tap('[data-action="result-tab"][data-value="salon"]');await tap('.winner .product-name');await wait(`!!document.querySelector('.detail-page')`);assert.match(await evaluate(`document.querySelector('.detail-page').textContent`),/公式情報確認日/);assert.ok(await evaluate(`document.querySelectorAll('.source-list a').length>0`));await tap('.page-top a');await wait(`!!document.querySelector('.results-page')`);assert.equal(await evaluate(`document.querySelector('.tabs .active').textContent`),'サロン系');check('商品詳細から戻っても結果タブ保持');
 await tap('.winner [data-action="favorite"]');assert.equal(await evaluate(`document.activeElement.dataset.action`),'favorite');await tap('.result-close a');await wait(`!!document.querySelector('.home')`);check('結果を閉じる・お気に入りフォーカス保持');
 await tap('#nav a[href="#search"]');await wait(`!!document.querySelector('#search-input')`);await type('#search-input','COTA');assert.equal(await evaluate(`document.querySelectorAll('.product-card').length`),2);
 await evaluate(`var savedInput=document.querySelector('#search-input');savedInput.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));savedInput.value='こ';savedInput.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,data:'こ'}));`);assert.equal(await evaluate(`savedInput===document.querySelector('#search-input')`),true);assert.equal(await evaluate(`document.querySelectorAll('.product-card').length`),2);await evaluate(`savedInput.value='プリュスオー';savedInput.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'プリュスオー'}));`);assert.equal(await evaluate(`document.querySelectorAll('.product-card').length`),2);check('変換中は入力欄・検索結果を保持し、確定で更新');
 await tap('.filter-panel summary');await evaluate(`var savedFilter=document.querySelector('[data-filter="price"]');savedFilter.focus();savedFilter.value='1500';savedFilter.dispatchEvent(new Event('change',{bubbles:true}));`);assert.equal(await evaluate(`document.activeElement===savedFilter`),true);assert.equal(await evaluate(`document.querySelectorAll('.product-card').length`),0);await tap('.empty [data-action="reset-filters"]');assert.equal(await evaluate(`document.querySelectorAll('.product-card').length`),6);assert.equal(await evaluate(`document.querySelector('#search-input').value`),'');check('検索0件から条件をクリア、フィルターのフォーカス維持');
 await evaluate(`savedFilter.value='3000';savedFilter.dispatchEvent(new Event('change',{bubbles:true}));`);assert.equal(await evaluate(`document.querySelectorAll('.product-card').length`),3);check('実価格による絞り込み');await tap('[data-action="reset-filters"]');
 for(let i=1;i<=4;i++)await tap(`.product-card:nth-child(${i}) [data-action="compare"]`);assert.match(await evaluate(`document.querySelector('#toast').textContent`),/最大3件/);await tap('#nav a[href="#saved"]');await wait(`!!document.querySelector('.saved-page')`);await tap('.saved-tabs a[href="#compare"]');await wait(`!!document.querySelector('table')`);assert.equal(await evaluate(`document.querySelectorAll('thead th').length`),4);await snap('repaired-mobile-compare');check('お気に入り・比較と3件上限');
 await tap('#nav a[href="#mypage"]');await wait(`!!document.querySelector('.mypage')`);assert.equal(await evaluate(`document.querySelectorAll('.history-card').length`),1);
 await tap('[data-action="edit-history"]');await wait(`document.querySelector('#memo-dialog').open`);await type('#memo-dialog [name="title"]','カラー後の記録');await type('#memo-dialog [name="memo"]','毛先のまとまりを見ていきたい。');await snap('repaired-mobile-memo');await tap('#memo-dialog [type="submit"]');await wait(`!document.querySelector('#memo-dialog').open`);assert.match(await evaluate(`document.querySelector('.history-card').textContent`),/カラー後の記録/);await send('Page.reload');await wait(`!!document.querySelector('.history-title')`);assert.match(await evaluate(`document.querySelector('.history-note').textContent`),/毛先/);check('履歴の名前・メモ保存と復元');
 await tap('[data-action="edit-history"]');await wait(`document.querySelector('#memo-dialog').open`);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27,nativeVirtualKeyCode:27});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27,nativeVirtualKeyCode:27});await wait(`!document.querySelector('#memo-dialog').open`);check('ダイアログをEscapeで閉じる');
 await tap('.history-preview');await wait(`!!document.querySelector('.history-difference')`);await tap('.history-difference summary');assert.match(await evaluate(`document.querySelector('.history-difference').textContent`),/前回の診断はまだありません/);await tap('[data-action="reuse-history"]');await atStep(8);await tap('[data-action="edit-step"][data-index="3"]');await atStep(4);await choose({finish:'light',priority:'light'});await tap('[data-action="next"]');await atStep(8);await tap('[data-action="next"]');await wait(`!!document.querySelector('.results-page')`);
 await tap('#nav a[href="#mypage"]');await wait(`document.querySelectorAll('.history-card').length===2`);await tap('.history-preview');await wait(`!!document.querySelector('.history-difference')`);await tap('.history-difference summary');assert.match(await evaluate(`document.querySelector('.history-difference').textContent`),/一番重視するもの/);assert.match(await evaluate(`document.querySelector('.history-difference').textContent`),/ポイント/);await snap('repaired-mobile-difference');check('前回と変わった回答・1位・同じ商品のスコア差');
 await tap('#nav a[href="#mypage"]');await wait(`!!document.querySelector('.mypage')`);await tap('[data-action="delete-history"]');await tap('[data-action="delete-history"]');assert.equal(await evaluate(`document.querySelectorAll('.history-card').length`),0);await send('Page.reload');await wait(`!!document.querySelector('.mypage')`);assert.equal(await evaluate(`document.querySelectorAll('.history-card').length`),0);await tap('[data-action="undo-history"]');await wait(`document.querySelectorAll('.history-card').length===2`);check('全履歴削除→再読み込みでも復活しない、元に戻すで2件復元');
 // Fault injection applies only to this isolated test profile.
 await evaluate(`var realSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Quota exceeded','QuotaExceededError')}`);
 await tap('#nav a[href="#search"]');await wait(`!!document.querySelector('#search-input')`);await tap('.product-card [data-action="favorite"]');assert.match(await evaluate(`document.querySelector('#toast').textContent`),/保存に失敗/);assert.equal(await evaluate(`document.querySelector('#save-status').hidden`),false);await tap('.product-card [data-action="favorite"]');
 await evaluate(`Storage.prototype.setItem=realSetItem`);await tap('#retry-save');assert.equal(await evaluate(`document.querySelector('#save-status').hidden`),true);check('保存失敗を通知し、最新の状態を再試行で保存');
 // History failure must never say the diagnosis is stored.
 await tap('#nav a[href="#mypage"]');await wait(`!!document.querySelector('.mypage')`);await tap('.history-preview');await wait(`!!document.querySelector('[data-action="reuse-history"]')`);await tap('[data-action="reuse-history"]');await atStep(8);await evaluate(`Storage.prototype.setItem=function(key,value){if(key==='hairmatch:history')throw new DOMException('Quota','QuotaExceededError');return realSetItem.call(this,key,value);}`);await evaluate(`document.querySelector('[data-action="next"]').click();document.querySelector('[data-action="next"]')?.click();`);await wait(`!!document.querySelector('.results-page')`);assert.match(await evaluate(`document.querySelector('.results-page').textContent`),/端末への保存待ち/);await evaluate('Storage.prototype.setItem=realSetItem');await tap('#retry-save');assert.match(await evaluate(`document.querySelector('.results-page').textContent`),/履歴に保存しました/);check('診断履歴の保存失敗と再試行');
 for(const width of [320,390,768,1440]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<768});for(const target of ['#saved','#mypage','#search']){await tap(`#nav a[href="${target}"]`);await wait(`!document.querySelector('.results-page')`);assert.equal(await evaluate(`document.documentElement.scrollWidth>innerWidth`),false,`${width} ${target}`);}check(`${width}pxで横方向のはみ出しなし`);}
 await tap('#nav a[href="#mypage"]');await wait(`!!document.querySelector('.mypage')`);assert.equal(await evaluate(`document.querySelectorAll('.history-card').length`),3);check('診断ボタンを連打しても履歴は1件だけ追加');await snap('repaired-desktop-mypage');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await snap('repaired-mobile-mypage');
 await wait(`Array.from(document.images).every(i=>i.complete)`);assert.equal(await evaluate(`Array.from(document.images).filter(i=>!i.naturalWidth).length`),0);assert.deepEqual(errors,[]);assert.deepEqual(failed.filter(x=>!x.endsWith('/favicon.ico')),[]);check('画像読み込みとブラウザ例外なし');
 await send('Browser.close');
}finally{socket?.close();child.kill();}

